import Head from "next/head";
import Image from "next/image";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";
import Header from "../components/Header";
import Messages from "../components/Messages";

export default function Home() {
	const { isAuthenticated, logout } = useMoralis();

	if (!isAuthenticated) return <Login />;

	return (
		<div className="h-screen overflow-y-scroll bg-gradient-to-b from-[#FC415A] to-[#591BC5] overflow-hidden">
			{/* <Image src="/new-bg.png" alt="" layout="fill" objectFit="cover" /> */}
			<Head>
				<title>Metaverse</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{/* Header */}
			<div className="max-w-screen-2xl mx-auto">
				<Header />
			{/* Messages */}
				<Messages />
			</div>
		</div>
	);
}
