import Head from "next/head";
import Login from "../components/Login";
import { useMoralis } from "react-moralis";

export default function Home() {
	
	const { isAuthenticated, logout } = useMoralis();

	if (!isAuthenticated) return <Login />
	
	return (
		<div className="h-screen flex flex-col justify-center items-center">
			<Head>
				<title>Metaverse</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>Welcome to the APP</h1>
			<button
			className="bg-yellow-500 p-4 mt-4 rounded-lg"
			onClick={logout}>Logout</button>
		</div>
	);
}
